#!/usr/bin/env bash
# Resume the lambda=0.5 Explorer run with the full TRC v5litepod-256 as the
# JAX training slice and a same-region v6e-64 as the vLLM rollout slice.
#
# Safety:
# - Uses existing TPUs only. It does not create TPUs, routers, or NAT.
# - Requires the TRC pod to have external IPs enabled.
# - Keeps artifacts HF-only; GCS artifact writes are disabled.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

export TRC2_PROJECT="${TRC2_PROJECT:?set TRC2_PROJECT to the GCP project id of the TRC allocation}"
export TRC2_ZONE="${TRC2_ZONE:-europe-west4-b}"
export TRC2_TPU_NAME="${TRC2_TPU_NAME:-trc2-v5lite256-ew4b-r1}"
export TRC2_EXPECTED_ACCELERATOR="${TRC2_EXPECTED_ACCELERATOR:-v5litepod-256}"
"$ROOT_DIR/scripts/trc2_v5lite256_guard.sh" "$@"

SOURCE_RUN="${SOURCE_RUN:-dapo16k_drgrpo_novelty05_hf_resume49_20260429_174651_wandbresume_parallelvllm}"
SOURCE_STEP="${SOURCE_STEP:-000100}"
RUN_STAMP="$(date +%Y%m%d_%H%M%S)"
export RUN_NAME="${RUN_NAME:-dapo16k_drgrpo_novelty05_trc256full_v6erollout_resume${SOURCE_STEP}_b4ga1_${RUN_STAMP}}"

# Full 64-worker / 256-chip train slice on TRC.
export TRAIN_TPU_PROJECT="${TRAIN_TPU_PROJECT:-$TRC2_PROJECT}"
export TRAIN_TPU_NAME="${TRAIN_TPU_NAME:-$TRC2_TPU_NAME}"
export TRAIN_ZONE="${TRAIN_ZONE:-$TRC2_ZONE}"
export TRAIN_WORKERS="${TRAIN_WORKERS:-0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63}"
export TPU_ACCELERATOR_TYPE="${TPU_ACCELERATOR_TYPE:-v5litepod-256}"
export TMX_USE_MANUAL_TPU_TOPOLOGY="${TMX_USE_MANUAL_TPU_TOPOLOGY:-1}"
export TMX_TPU_HOST_BOUNDS="${TMX_TPU_HOST_BOUNDS:-8,8,1}"
export JAX_INITIALIZATION_TIMEOUT="${JAX_INITIALIZATION_TIMEOUT:-1800}"
export JAX_HEARTBEAT_TIMEOUT_SECONDS="${JAX_HEARTBEAT_TIMEOUT_SECONDS:-900}"

# Same-region rollout slice. This avoids the unsupported TRC partial-submesh
# train/serve split while still using all 256 TRC chips for training.
export SERVE_TPU_PROJECT="${SERVE_TPU_PROJECT:?set SERVE_TPU_PROJECT to the GCP project id of the serving TPU}"
export SERVE_TPU_NAME="${SERVE_TPU_NAME:?set SERVE_TPU_NAME to the serving (vLLM) TPU VM (slice) name}"
export SERVE_ZONE="${SERVE_ZONE:-europe-west4-a}"
export SERVE_WORKERS="${SERVE_WORKERS:-0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15}"
export TMX_SINGLE_TPU_DISJOINT_TRAIN_SERVE=0
export TMX_REQUIRE_SAME_REGION_TPU="${TMX_REQUIRE_SAME_REGION_TPU:-1}"
export TMX_ALLOW_CROSS_REGION_TPU="${TMX_ALLOW_CROSS_REGION_TPU:-0}"

export REMOTE_REPO="${REMOTE_REPO:?set REMOTE_REPO to the absolute repo path on every TPU worker}"
export RUNS_ROOT="${RUNS_ROOT:?set RUNS_ROOT to the absolute runs directory on the TPU VM}"
export MODEL_NAME="${MODEL_NAME:-Qwen/Qwen3-1.7B}"
export INIT_CHECKPOINT="${INIT_CHECKPOINT-hf://SaifPunjwani/two-model-exploration-checkpoints/${SOURCE_RUN}/explorer/checkpoints/step_${SOURCE_STEP}}"

# DAPO / Dr.GRPO / novelty contract.
export MAX_PROMPT_LEN="${MAX_PROMPT_LEN:-2048}"
export MAX_COMPLETION_LEN="${MAX_COMPLETION_LEN:-16384}"
export MAX_TOTAL_LEN="${MAX_TOTAL_LEN:-18432}"
export GRPO_NUM_GENERATIONS="${GRPO_NUM_GENERATIONS:-16}"
export GRPO_BATCH_SIZE="${GRPO_BATCH_SIZE:-4}"
export GRPO_GRAD_ACCUM="${GRPO_GRAD_ACCUM:-4}"
export TMX_EXPECTED_GRPO_BATCH_SIZE="$GRPO_BATCH_SIZE"
export TMX_EXPECTED_GRPO_GRAD_ACCUM="$GRPO_GRAD_ACCUM"
# Generate fewer real prompt groups per step and pad to the full train tensor.
# This keeps the 256-chip train mesh contract while avoiding 256 long rollouts
# before every update.
export TMX_EFFECTIVE_PROMPTS_PER_STEP="${TMX_EFFECTIVE_PROMPTS_PER_STEP:-4}"
export GRPO_MAX_STEPS="${GRPO_MAX_STEPS:-300}"
export GRPO_UPDATES_PER_ROLLOUT="${GRPO_UPDATES_PER_ROLLOUT:-1}"
export TMX_EXPECTED_GRPO_UPDATES_PER_ROLLOUT="$GRPO_UPDATES_PER_ROLLOUT"
export GRPO_LR="${GRPO_LR:-5e-6}"
export GRPO_CLIP_EPSILON=0.2
export GRPO_CLIP_EPSILON_HIGH=0.28
export GRPO_KL_BETA=0.0
export GRPO_ADVANTAGE_NORMALIZATION=none
export DYNAMIC_SAMPLING=true
export DYNAMIC_SAMPLING_MAX_ATTEMPTS="${DYNAMIC_SAMPLING_MAX_ATTEMPTS:-8}"
export DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT="${DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT:-1}"
export TMX_DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT="$DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT"
export MASK_TRUNCATED_COMPLETIONS=false
export SOFT_OVERLONG_EXPECTED_LEN="${SOFT_OVERLONG_EXPECTED_LEN:-13107}"
export SOFT_OVERLONG_CACHE_LEN="${SOFT_OVERLONG_CACHE_LEN:-3277}"
export REWARD_CORRECT=1.0
export REWARD_INCORRECT=-1.0
export FORMAT_PENALTY_WEIGHT=0.0
export NONTERMINATION_PENALTY=0.0
export INVALID_ANSWER_PENALTY=0.0
export LAMBDA_NOVELTY="${LAMBDA_NOVELTY:-0.5}"
export INCORRECT_NOVELTY_SCALE="${INCORRECT_NOVELTY_SCALE:-1.0}"
export NOVELTY_FEATURE_SOURCE=multilayer
export NOVELTY_LAYERS="${NOVELTY_LAYERS:-7,14,21}"
export NOVELTY_LAYER_POOL=mean
export NOVELTY_LAYER_AGG=mean
export NOVELTY_METRIC=sqrt_mse
export NOVELTY_TEXT_CONTRACT=full_raw
export GATE_NOVELTY_BY_QUALITY=false
export NOVELTY_FEATURE_MAX_LENGTH="${NOVELTY_FEATURE_MAX_LENGTH:-$MAX_TOTAL_LEN}"
export TMX_DAPO_DRGRPO_FULL_CONTRACT=1
export TMX_DAPO_DRGRPO_CONTRACT_COMPLETION_LEN="$MAX_COMPLETION_LEN"
export TMX_DAPO_DRGRPO_CONTRACT_SOFT_OVERLONG_EXPECTED_LEN="$SOFT_OVERLONG_EXPECTED_LEN"
export TMX_DAPO_DRGRPO_CONTRACT_SOFT_OVERLONG_CACHE_LEN="$SOFT_OVERLONG_CACHE_LEN"
export TMX_ALLOW_LONG_COMPLETION_TRAIN=1
export TMX_DISABLE_ROLLOUT_DIVERSITY="${TMX_DISABLE_ROLLOUT_DIVERSITY:-1}"

# vLLM rollout settings.
export VLLM_MAX_MODEL_LEN="${VLLM_MAX_MODEL_LEN:-$MAX_TOTAL_LEN}"
export VLLM_MAX_NUM_BATCHED_TOKENS="${VLLM_MAX_NUM_BATCHED_TOKENS:-$MAX_TOTAL_LEN}"
export VLLM_MAX_NUM_SEQS="${VLLM_MAX_NUM_SEQS:-1}"
export VLLM_MAX_NUM_SEQS_CANDIDATES="${VLLM_MAX_NUM_SEQS_CANDIDATES:-1 2}"
export VLLM_TP_SIZE="${VLLM_TP_SIZE:-4}"
export VLLM_TP_SIZE_CANDIDATES="${VLLM_TP_SIZE_CANDIDATES:-4}"
export VLLM_CONCURRENCY="${VLLM_CONCURRENCY:-64}"
export VLLM_FANOUT_PER_PROMPT="${VLLM_FANOUT_PER_PROMPT:-4}"
export TMX_ROLLOUT_BACKEND="${TMX_ROLLOUT_BACKEND:-adaptive_vllm_http}"
export TMX_HTTP_POOL_MAXSIZE="${TMX_HTTP_POOL_MAXSIZE:-256}"
export TMX_VLLM_ENDPOINT_MAX_INFLIGHT="${TMX_VLLM_ENDPOINT_MAX_INFLIGHT:-1}"
export VLLM_ENABLE_CHUNKED_PREFILL="${VLLM_ENABLE_CHUNKED_PREFILL:-1}"
export VLLM_V1_USE_PREFILL_DECODE_ATTENTION="${VLLM_V1_USE_PREFILL_DECODE_ATTENTION:-1}"
export VLLM_XLA_CACHE_TAG="${VLLM_XLA_CACHE_TAG:-v6e_tp4_pda1_mlen${VLLM_MAX_MODEL_LEN}_mbt${VLLM_MAX_NUM_BATCHED_TOKENS}}"
export ALLOW_DEGRADED_SERVE="${ALLOW_DEGRADED_SERVE:-1}"
export MIN_HEALTHY_SERVE_WORKERS="${MIN_HEALTHY_SERVE_WORKERS:-12}"
export TMX_VLLM_RELOAD_MIN_HEALTHY_WORKERS="${TMX_VLLM_RELOAD_MIN_HEALTHY_WORKERS:-12}"
export TMX_VLLM_TUNNEL_FROM_TRAIN_SOURCE="${TMX_VLLM_TUNNEL_FROM_TRAIN_SOURCE:-1}"
export TMX_VLLM_TUNNEL_BASE_PORT="${TMX_VLLM_TUNNEL_BASE_PORT:-18000}"
export TMX_VLLM_TUNNEL_WARMUP_SECONDS="${TMX_VLLM_TUNNEL_WARMUP_SECONDS:-8}"
# On 64-host TRC pods, libtpu can map JAX process 0 to a physical worker other
# than gcloud worker 0. Rollouts are issued by JAX process 0, so expose the
# worker-0 IAP tunnels through proxy URLs reachable from every train worker.
export TMX_VLLM_RANK_AGNOSTIC_PROXY="${TMX_VLLM_RANK_AGNOSTIC_PROXY:-1}"

# HF-only artifacts and compact W&B logging.
export TMX_ARTIFACT_BACKEND=hf
export TMX_ALLOW_GCS_ARTIFACTS=0
export TMX_GCS_CHECKPOINT_BASE=
export TMX_HF_CHECKPOINT_REPO="${TMX_HF_CHECKPOINT_REPO:-SaifPunjwani/two-model-exploration-checkpoints}"
export TMX_HF_MODEL_REPO="${TMX_HF_MODEL_REPO:-SaifPunjwani/two-model-exploration-models}"
export TMX_HF_DATASET_REPO="${TMX_HF_DATASET_REPO:-SaifPunjwani/two-model-exploration-checkpoints}"
export TMX_HF_REPO_TYPE=dataset
export TMX_HF_ARTIFACT_PREFIX="${TMX_HF_ARTIFACT_PREFIX:-$RUN_NAME}"
export TMX_REQUIRE_HF_ARTIFACT_UPLOAD="${TMX_REQUIRE_HF_ARTIFACT_UPLOAD:-1}"
export TMX_HF_CHECKPOINT_EVERY_STEPS="${TMX_HF_CHECKPOINT_EVERY_STEPS:-10}"
export TMX_HF_CHECKPOINT_FIRST_STEP="${TMX_HF_CHECKPOINT_FIRST_STEP:-110}"
export SAVE_EVERY_STEPS="${SAVE_EVERY_STEPS:-10}"
export TMX_LOCAL_CHECKPOINT_EVERY_STEPS="${TMX_LOCAL_CHECKPOINT_EVERY_STEPS:-0}"
export TMX_SAVE_OPT_STATE=0
export TMX_RESTORE_OPT_STATE=0
export TMX_INIT_EMPTY_FOR_RESTORE="${TMX_INIT_EMPTY_FOR_RESTORE:-1}"
export TMX_WANDB_SINGLE_RUN=1
export TMX_WANDB_COMPACT=1
export TMX_WANDB_MINIMAL=1
export TMX_WANDB_EVAL_PROGRESS=0

# Same-region external reload from the full train slice to v6e rollout workers.
export TMX_PREFETCH_ROLLOUTS=1
export TMX_TRAIN_VLLM_RELOAD_EVERY_STEPS="${TMX_TRAIN_VLLM_RELOAD_EVERY_STEPS:-10}"
export TMX_TRAIN_VLLM_RELOAD_FIRST_STEP="${TMX_TRAIN_VLLM_RELOAD_FIRST_STEP:-110}"
export TMX_TRAIN_VLLM_RELOAD_ON_RESUME=1
export TMX_TRAIN_VLLM_RELOAD_MODE="${TMX_TRAIN_VLLM_RELOAD_MODE:-external}"
export TMX_VLLM_RELOAD_TRANSPORT="${TMX_VLLM_RELOAD_TRANSPORT:-hf}"
export TMX_HF_MIRROR_VLLM_EXPORTS="${TMX_HF_MIRROR_VLLM_EXPORTS:-1}"
export TMX_EXTERNAL_VLLM_RELOAD_WAIT=1
export TMX_EXTERNAL_VLLM_RELOAD_REQUIRED=1
export TMX_EXTERNAL_VLLM_RELOAD_RETRY_ON_FAIL=1
export TMX_EXTERNAL_VLLM_RELOAD_TIMEOUT="${TMX_EXTERNAL_VLLM_RELOAD_TIMEOUT:-7200}"
export TMX_VLLM_RELOAD_ALLOW_PARALLEL=1
export TMX_VLLM_RELOAD_PARALLELISM="${TMX_VLLM_RELOAD_PARALLELISM:-8}"
export TMX_TRAIN_LAUNCH_STABILITY_SECONDS="${TMX_TRAIN_LAUNCH_STABILITY_SECONDS:-3}"
export TMX_FAST_CLEAN_SLICE="${TMX_FAST_CLEAN_SLICE:-1}"

export TMX_AIME_PROBE_EVERY_STEPS="${TMX_AIME_PROBE_EVERY_STEPS:-10}"
export TMX_AIME_PROBE_NUM_PROBLEMS="${TMX_AIME_PROBE_NUM_PROBLEMS:-4}"
export TMX_AIME_PROBE_NUM_ROLLOUTS="${TMX_AIME_PROBE_NUM_ROLLOUTS:-4}"
export TMX_AIME_PROBE_MAX_TOKENS="${TMX_AIME_PROBE_MAX_TOKENS:-16384}"
export TMX_AIME_PROBE_CONCURRENCY="${TMX_AIME_PROBE_CONCURRENCY:-32}"

# The package tarball fanout is large and worth keeping. The worker-script
# bundle is tiny; direct SCP avoids rare truncated HTTP tar reads on 64-host
# TRC fanout.
export TMX_FAST_PACKAGE_FANOUT="${TMX_FAST_PACKAGE_FANOUT:-1}"
export TMX_FAST_WORKER_SCRIPT_FANOUT="${TMX_FAST_WORKER_SCRIPT_FANOUT:-0}"

echo "[trc256-fulltrain] run=$RUN_NAME"
echo "[trc256-fulltrain] checkpoint=$INIT_CHECKPOINT"
echo "[trc256-fulltrain] train=$TRAIN_TPU_PROJECT/$TRAIN_ZONE/$TRAIN_TPU_NAME workers=64 host_bounds=$TMX_TPU_HOST_BOUNDS"
echo "[trc256-fulltrain] serve=$SERVE_TPU_PROJECT/$SERVE_ZONE/$SERVE_TPU_NAME workers=16"
echo "[trc256-fulltrain] contract: lambda=$LAMBDA_NOVELTY G=$GRPO_NUM_GENERATIONS batch=$GRPO_BATCH_SIZE completion=$MAX_COMPLETION_LEN clip=$GRPO_CLIP_EPSILON/$GRPO_CLIP_EPSILON_HIGH KL=$GRPO_KL_BETA"

exec "$ROOT_DIR/scripts/restart_dapo_drgrpo_twoslice.sh"
