#!/usr/bin/env bash
set -euo pipefail

export RUN_NAME="dapo16k_drgrpo_novelty05_extend_saif_v6e_ew4a_$(date +%Y%m%d_%H%M%S)"
export SOURCE_RUN="dapo16k_drgrpo_novelty05_hf_resume49_20260429_174651_wandbresume_parallelvllm"
export SOURCE_STEP="000100"
export INIT_CHECKPOINT="hf://SaifPunjwani/two-model-exploration-checkpoints/${SOURCE_RUN}/explorer/checkpoints/step_${SOURCE_STEP}"

export GRPO_BATCH_SIZE=1
export GRPO_GRAD_ACCUM=1
export GRPO_NUM_GENERATIONS=16
export GRPO_MAX_STEPS=200
export MAX_PROMPT_LEN=2048
export MAX_COMPLETION_LEN=16384
export MAX_TOTAL_LEN=18432
export SOFT_OVERLONG_EXPECTED_LEN=13107
export SOFT_OVERLONG_CACHE_LEN=3277

export LAMBDA_NOVELTY=0.5
export INCORRECT_NOVELTY_SCALE=1.0
export GRPO_CLIP_EPSILON=0.2
export GRPO_CLIP_EPSILON_HIGH=0.28
export GRPO_KL_BETA=0.0
export GRPO_ADVANTAGE_NORMALIZATION=none
export DYNAMIC_SAMPLING=true
export DYNAMIC_SAMPLING_MAX_ATTEMPTS=8
export DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT=1
export REWARD_CORRECT=1.0
export REWARD_INCORRECT=-1.0
export FORMAT_PENALTY_WEIGHT=0.0
export NONTERMINATION_PENALTY=0.0
export INVALID_ANSWER_PENALTY=0.0

export TRC2_PROJECT="${TRC2_PROJECT:?set TRC2_PROJECT to the GCP project id of the TRC allocation}"
export TRC2_ZONE=europe-west4-a
export TRC2_TPU_NAME="${TRC2_TPU_NAME:?set TRC2_TPU_NAME to the TPU VM name}"
export TRC2_EXPECTED_ACCELERATOR=v6e-64
export TPU_ACCELERATOR_TYPE=v6e-64
export TRAIN_WORKERS="0 1 2 3 4 5 6 7"
export SERVE_WORKERS="8 9 10 11 12 13 14 15"
export TMX_SINGLE_TPU_DISJOINT_TRAIN_SERVE=1
export TMX_REQUIRE_SAME_REGION_TPU=1
export TMX_ALLOW_CROSS_REGION_TPU=0

export VLLM_CONCURRENCY=64
export VLLM_FANOUT_PER_PROMPT=16
export MIN_HEALTHY_SERVE_WORKERS=6
export TMX_VLLM_RELOAD_MIN_HEALTHY_WORKERS=6
export ALLOW_DEGRADED_SERVE=1

export TMX_ARTIFACT_BACKEND=hf
export TMX_ALLOW_GCS_ARTIFACTS=0
export TMX_HF_CHECKPOINT_REPO=SaifPunjwani/two-model-exploration-checkpoints
export TMX_HF_ARTIFACT_PREFIX="$RUN_NAME"
export TMX_REQUIRE_HF_ARTIFACT_UPLOAD=1
export TMX_HF_CHECKPOINT_EVERY_STEPS=25
export SAVE_EVERY_STEPS=25

export TMX_TRAIN_VLLM_RELOAD_MODE=direct
export TMX_TRAIN_VLLM_RELOAD_EVERY_STEPS=25
export TMX_TRAIN_VLLM_RELOAD_FIRST_STEP=125
export TMX_AIME_PROBE_EVERY_STEPS=25
export TMX_AIME_PROBE_NUM_PROBLEMS=6
export TMX_AIME_PROBE_NUM_ROLLOUTS=4
export TMX_WANDB_SINGLE_RUN=1
export TMX_WANDB_COMPACT=1
export TMX_WANDB_MINIMAL=1

scripts/trc2_v5lite256_guard.sh
scripts/launch_trc2_v5lite256_tmx_jax_resume.sh
