#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

TPU_NAME="${TPU_NAME:?set TPU_NAME to the TPU VM (slice) name}"
ZONE="${ZONE:-europe-west4-b}"
TPU_PROXY_JUMP_ALIAS="${TPU_PROXY_JUMP_ALIAS:?set TPU_PROXY_JUMP_ALIAS to the ssh alias used as a jump host, or 'none'}"
if [ "$TPU_PROXY_JUMP_ALIAS" = "none" ]; then
  TPU_PROXY_JUMP_ALIAS=
fi
MODEL_NAME="${MODEL_NAME:-Qwen/Qwen3-1.7B}"
RUN_PREFIX="${RUN_PREFIX:-ew4b_qwen3_1p7b_avg32_resume}"
RUN_ARTIFACT_GCS_PREFIX="${RUN_ARTIFACT_GCS_PREFIX:-gs://llmvae-checkpoints/two-model-exploration/ew4b_qwen3_avg32_resume}"
VLLM_ENV_CACHE_GCS_URI="${VLLM_ENV_CACHE_GCS_URI:-gs://llmvae-checkpoints/two-model-exploration/shared_envs/v5lite_vllm_tpu_0.13.3_py311.tar.gz}"
MAX_BENCHMARK="${MAX_BENCHMARK:-30}"
BENCHMARK_NUM_ROLLOUTS="${BENCHMARK_NUM_ROLLOUTS:-32}"
BENCHMARK_ROLLOUT_TEMPERATURE="${BENCHMARK_ROLLOUT_TEMPERATURE:-1.0}"
BENCHMARK_ROLLOUT_TOP_P="${BENCHMARK_ROLLOUT_TOP_P:-1.0}"
BENCHMARK_ROLLOUT_TOP_K="${BENCHMARK_ROLLOUT_TOP_K:-0}"
BENCHMARK_ROLLOUT_MAX_COMPLETION_LEN="${BENCHMARK_ROLLOUT_MAX_COMPLETION_LEN:-16384}"
REQUEST_CONCURRENCY="${REQUEST_CONCURRENCY:-32}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-32768}"
MAX_NUM_SEQS="${MAX_NUM_SEQS:-32}"
MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-65536}"
WORKERS_THINK="${WORKERS_THINK:-0,1,2,3,4,5,6,7}"
WORKERS_NOTHINK="${WORKERS_NOTHINK:-8,9,10,11,12,13,14,15}"

log() {
  printf '[ew4b-qwen3] %s\n' "$*"
}

launch_mode() {
  local mode="$1"
  local workers="$2"
  local group="$3"
  local run_prefix="${RUN_PREFIX}_${mode}"

  log "launching mode=$mode workers=[$workers] run_prefix=$run_prefix"
  TPU_NAME="$TPU_NAME" \
  ZONE="$ZONE" \
  TPU_PROXY_JUMP_ALIAS="$TPU_PROXY_JUMP_ALIAS" \
  MODEL_NAME="$MODEL_NAME" \
  SERVED_MODEL_NAME="$MODEL_NAME" \
  TOKENIZER_NAME="$MODEL_NAME" \
  RUN_PREFIX="$run_prefix" \
  WORKERS="$workers" \
  EXCLUDE_WORKERS= \
  WAIT_FOR_COMPLETION=0 \
  ALLOW_DIRTY=1 \
  BOOTSTRAP_VLLM=1 \
  SYNC_REPO=1 \
  BENCHMARK_DATASET_NAME=aime_2024 \
  MAX_BENCHMARK="$MAX_BENCHMARK" \
  BENCHMARK_NUM_ROLLOUTS="$BENCHMARK_NUM_ROLLOUTS" \
  BENCHMARK_ROLLOUT_TEMPERATURE="$BENCHMARK_ROLLOUT_TEMPERATURE" \
  BENCHMARK_ROLLOUT_TOP_P="$BENCHMARK_ROLLOUT_TOP_P" \
  BENCHMARK_ROLLOUT_TOP_K="$BENCHMARK_ROLLOUT_TOP_K" \
  BENCHMARK_ROLLOUT_MAX_COMPLETION_LEN="$BENCHMARK_ROLLOUT_MAX_COMPLETION_LEN" \
  BENCHMARK_ROLLOUT_PASS_K=1,4,8,16,32 \
  REQUEST_CONCURRENCY="$REQUEST_CONCURRENCY" \
  MAX_MODEL_LEN="$MAX_MODEL_LEN" \
  MAX_NUM_SEQS="$MAX_NUM_SEQS" \
  MAX_NUM_BATCHED_TOKENS="$MAX_NUM_BATCHED_TOKENS" \
  THINKING_MODE="$mode" \
  USE_WANDB=1 \
  WANDB_GROUP="$group" \
  RUN_ARTIFACT_GCS_PREFIX="${RUN_ARTIFACT_GCS_PREFIX%/}/${mode}" \
  RUN_SYNC_INTERVAL_SECONDS="${RUN_SYNC_INTERVAL_SECONDS:-90}" \
  VLLM_ENV_CACHE_GCS_URI="$VLLM_ENV_CACHE_GCS_URI" \
  BOOTSTRAP_PARALLELISM="${BOOTSTRAP_PARALLELISM:-4}" \
  bash scripts/run_tpu_slice_vllm_sharded_aime.sh
}

launch_mode think "$WORKERS_THINK" "${WANDB_GROUP_THINK:-ew4b_qwen3_think_avg32}"
launch_mode no_think "$WORKERS_NOTHINK" "${WANDB_GROUP_NOTHINK:-ew4b_qwen3_nothink_avg32}"

log "remote shard launches issued; rerun with the same RUN_PREFIX to reuse per-problem checkpoints"
