#!/usr/bin/env bash
# Fresh lambda=0.25 Explorer run on one v5litepod-64 slice:
# - train workers 0..3
# - rollout workers 4..15
# This is the safe fallback when TRC v6e train slices are occupied.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

RUN_STAMP="$(date +%Y%m%d_%H%M%S)"
export RUN_NAME="${RUN_NAME:-dapo16k_drgrpo_novelty025_saif_uc1a_split_${RUN_STAMP}}"
export TMX_JAX_REPO="${TMX_JAX_REPO:-$(cd "$ROOT/../tmx-jax" && pwd)}"

export TRAIN_TPU_PROJECT="${TRAIN_TPU_PROJECT:?set TRAIN_TPU_PROJECT to the GCP project id of the training TPU}"
export TRAIN_TPU_NAME="${TRAIN_TPU_NAME:?set TRAIN_TPU_NAME to the training TPU VM (slice) name}"
export TRAIN_ZONE="${TRAIN_ZONE:-us-central1-a}"
export TRAIN_WORKERS="${TRAIN_WORKERS:-0 1 2 3}"

export SERVE_TPU_PROJECT="${SERVE_TPU_PROJECT:-$TRAIN_TPU_PROJECT}"
export SERVE_TPU_NAME="${SERVE_TPU_NAME:-$TRAIN_TPU_NAME}"
export SERVE_ZONE="${SERVE_ZONE:-$TRAIN_ZONE}"
export SERVE_WORKERS="${SERVE_WORKERS:-4 5 6 7 8 9 10 11 12 13 14 15}"
export TMX_SINGLE_TPU_DISJOINT_TRAIN_SERVE=1
export TMX_REQUIRE_SAME_REGION_TPU=1
export TMX_ALLOW_CROSS_REGION_TPU=0

export TPU_ACCELERATOR_TYPE="${TPU_ACCELERATOR_TYPE:-v5litepod-64}"
export TMX_USE_MANUAL_TPU_TOPOLOGY="${TMX_USE_MANUAL_TPU_TOPOLOGY:-1}"
export TMX_TPU_HOST_BOUNDS="${TMX_TPU_HOST_BOUNDS:-2,2,1}"

export BOOTSTRAP_SERVE_VLLM="${BOOTSTRAP_SERVE_VLLM:-1}"
export CLEAN_SERVE_SLICE="${CLEAN_SERVE_SLICE:-1}"
export VERIFY_EXISTING_SERVE_VLLM="${VERIFY_EXISTING_SERVE_VLLM:-0}"
export CLEAN_TRAIN_SLICE="${CLEAN_TRAIN_SLICE:-1}"
export ALLOW_DEGRADED_SERVE="${ALLOW_DEGRADED_SERVE:-1}"
export MIN_HEALTHY_SERVE_WORKERS="${MIN_HEALTHY_SERVE_WORKERS:-9}"
export TMX_PARALLEL_VLLM_HEALTH="${TMX_PARALLEL_VLLM_HEALTH:-1}"
export TMX_FAST_CLEAN_SLICE="${TMX_FAST_CLEAN_SLICE:-1}"
export TMX_VLLM_POST_BOOTSTRAP_WARMUP_SECONDS="${TMX_VLLM_POST_BOOTSTRAP_WARMUP_SECONDS:-120}"

export MODEL_NAME="${MODEL_NAME:-Qwen/Qwen3-1.7B}"
export MAX_PROMPT_LEN=2048
export MAX_COMPLETION_LEN="${MAX_COMPLETION_LEN:-16384}"
export MAX_TOTAL_LEN="${MAX_TOTAL_LEN:-18432}"
export GRPO_BATCH_SIZE="${GRPO_BATCH_SIZE:-1}"
export GRPO_GRAD_ACCUM="${GRPO_GRAD_ACCUM:-1}"
export GRPO_NUM_GENERATIONS=16
export GRPO_MAX_STEPS="${GRPO_MAX_STEPS:-100}"
export GRPO_LR="${GRPO_LR:-5e-6}"
export GRPO_CLIP_EPSILON=0.2
export GRPO_CLIP_EPSILON_HIGH=0.28
export GRPO_KL_BETA=0.0
export GRPO_ADVANTAGE_NORMALIZATION=none
export GRPO_UPDATES_PER_ROLLOUT=1
export TMX_EXPECTED_GRPO_UPDATES_PER_ROLLOUT=1
export DYNAMIC_SAMPLING=true
export DYNAMIC_SAMPLING_MAX_ATTEMPTS="${DYNAMIC_SAMPLING_MAX_ATTEMPTS:-2}"
export DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT="${DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT:-2}"
export TMX_DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT="$DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT"
export MASK_TRUNCATED_COMPLETIONS=false
export SOFT_OVERLONG_EXPECTED_LEN="${SOFT_OVERLONG_EXPECTED_LEN:-13107}"
export SOFT_OVERLONG_CACHE_LEN="${SOFT_OVERLONG_CACHE_LEN:-3277}"
export REWARD_CORRECT=1.0
export REWARD_INCORRECT=-1.0
export FORMAT_PENALTY_WEIGHT=0.0
export NONTERMINATION_PENALTY=0.0
export INVALID_ANSWER_PENALTY=0.0
export LAMBDA_NOVELTY=0.25
export INCORRECT_NOVELTY_SCALE=1.0
export NOVELTY_FEATURE_SOURCE=multilayer
export NOVELTY_LAYERS=7,14,21
export NOVELTY_LAYER_POOL=mean
export NOVELTY_LAYER_AGG=mean
export NOVELTY_METRIC=sqrt_mse
export NOVELTY_TEXT_CONTRACT=full_raw
export NOVELTY_FEATURE_MAX_LENGTH="$MAX_TOTAL_LEN"
export GATE_NOVELTY_BY_QUALITY=false

export TMX_PIPELINE_STAGE=explorer_novelty
export TMX_PIPELINE_STOP_AFTER_EXPLORER=1
export TMX_FRESH_RUN=1
export INIT_CHECKPOINT=

export VLLM_MAX_MODEL_LEN="$MAX_TOTAL_LEN"
export VLLM_MAX_NUM_SEQS="${VLLM_MAX_NUM_SEQS:-1}"
export VLLM_MAX_NUM_SEQS_CANDIDATES="${VLLM_MAX_NUM_SEQS_CANDIDATES:-1}"
export VLLM_MAX_NUM_BATCHED_TOKENS="$MAX_TOTAL_LEN"
export VLLM_TP_SIZE=4
export VLLM_TP_SIZE_CANDIDATES=4
export VLLM_CONCURRENCY="${VLLM_CONCURRENCY:-144}"
export VLLM_FANOUT_PER_PROMPT=16
export TMX_VLLM_ENDPOINT_MAX_INFLIGHT="${TMX_VLLM_ENDPOINT_MAX_INFLIGHT:-1}"
export VLLM_ENABLE_CHUNKED_PREFILL=1
export VLLM_V1_USE_PREFILL_DECODE_ATTENTION=1
export VLLM_XLA_CACHE_TAG="${VLLM_XLA_CACHE_TAG:-v5lite64_tp4_pda1_mlen${MAX_TOTAL_LEN}_mbt${MAX_TOTAL_LEN}}"
export TMX_VLLM_RANDOMIZE_SEEDS=1
export TMX_VLLM_SEED_MODE=prompt_nonce
export TMX_VLLM_SEED_API_FALLBACK=1
export TMX_VLLM_SEED_BASE="$RUN_NAME"
export TMX_VLLM_FANOUT_NONCE="$RUN_NAME"

export TMX_TRAIN_VLLM_RELOAD_MODE=external
export TMX_TRAIN_VLLM_RELOAD_EVERY_STEPS=10
export TMX_TRAIN_VLLM_RELOAD_FIRST_STEP=10
export TMX_TRAIN_VLLM_RELOAD_ON_RESUME=0
export TMX_EXTERNAL_VLLM_RELOAD_REQUIRED=1
export TMX_EXTERNAL_VLLM_RELOAD_RETRY_ON_FAIL=1
export TMX_VLLM_RELOAD_MIN_HEALTHY_WORKERS="${TMX_VLLM_RELOAD_MIN_HEALTHY_WORKERS:-9}"

export SAVE_EVERY_STEPS=10
export TMX_HF_CHECKPOINT_EVERY_STEPS=10
export TMX_HF_CHECKPOINT_FIRST_STEP=10
export TMX_ARTIFACT_BACKEND=hf
export TMX_ALLOW_GCS_ARTIFACTS=0
export TMX_GCS_CHECKPOINT_BASE=
export TMX_HF_CHECKPOINT_REPO="${TMX_HF_CHECKPOINT_REPO:-SaifPunjwani/two-model-exploration-checkpoints}"
export TMX_HF_MODEL_REPO="${TMX_HF_MODEL_REPO:-SaifPunjwani/two-model-exploration-models}"
export TMX_HF_DATASET_REPO="${TMX_HF_DATASET_REPO:-SaifPunjwani/two-model-exploration-checkpoints}"
export TMX_HF_REPO_TYPE=dataset
export TMX_HF_ARTIFACT_PREFIX="$RUN_NAME"
export TMX_REQUIRE_HF_ARTIFACT_UPLOAD="${TMX_REQUIRE_HF_ARTIFACT_UPLOAD:-1}"
export TMX_WANDB_MINIMAL=1
export TMX_WANDB_SINGLE_RUN=1
export WANDB_PROJECT="${WANDB_PROJECT:-two-model-explore}"
export WANDB_ENTITY="${WANDB_ENTITY:-}"

echo "[lambda025-saif-split] run=$RUN_NAME"
echo "[lambda025-saif-split] train=$TRAIN_TPU_PROJECT/$TRAIN_ZONE/$TRAIN_TPU_NAME workers=[$TRAIN_WORKERS]"
echo "[lambda025-saif-split] serve=$SERVE_TPU_PROJECT/$SERVE_ZONE/$SERVE_TPU_NAME workers=[$SERVE_WORKERS]"
echo "[lambda025-saif-split] contract: lambda=$LAMBDA_NOVELTY G=$GRPO_NUM_GENERATIONS completion=$MAX_COMPLETION_LEN clip=$GRPO_CLIP_EPSILON/$GRPO_CLIP_EPSILON_HIGH KL=$GRPO_KL_BETA"

exec "$ROOT/scripts/restart_dapo_drgrpo_twoslice.sh"
