#!/usr/bin/env bash
set -euo pipefail
#
# Launch Qwen3-1.7B two-model training with a fit-safe DAPO-think canary.
#
# Addresses the methodological feedback while keeping the single-chip TPU path
# inside a range that has a chance to survive more than one GRPO step:
#   1. Random problem selection (not solvable-only)
#   2. Standard \boxed{} answer format (via reasoning_final style)
#   3. Thinking mode enabled for math reasoning
#   4. Shorter canary budget (12 Explorer steps, not 48)
#   5. Moderate generation lengths instead of the previously oversized 1024/768 path
#

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

TPU_NAME="${TPU_NAME:?set TPU_NAME to the TPU VM (slice) name}"
ZONE="${ZONE:-europe-west4-a}"

QUEUE_TAG="${QUEUE_TAG:-ew4a_qwen3_1p7b_dapo_standard}"
RUN_ARTIFACT_GCS_PREFIX="${RUN_ARTIFACT_GCS_PREFIX:-gs://llmvae-checkpoints/two-model-exploration/ew4a_qwen3_dapo_standard}"

log() {
  printf '[ew4a-dapo-std] %s\n' "$*"
}

log "launching Qwen3 two-model fit-safe DAPO-think canary"

# --- XLA and TPU tuning ---
TMX_GRPO_GRAD_CKPT="${TMX_GRPO_GRAD_CKPT:-1}" \
TMX_XLA_SAFE_GENERATE="${TMX_XLA_SAFE_GENERATE:-1}" \
TMX_DEBUG_GENERATE="${TMX_DEBUG_GENERATE:-0}" \
TMX_DISABLE_BF16="${TMX_DISABLE_BF16:-0}" \
TMX_XLA_SKIP_LOADER_MARK_STEP="${TMX_XLA_SKIP_LOADER_MARK_STEP:-1}" \
TMX_XLA_INCREMENTAL_GENERATE="${TMX_XLA_INCREMENTAL_GENERATE:-1}" \
TMX_RESUME_TRAINING="${TMX_RESUME_TRAINING:-1}" \
TMX_SKIP_INTERMEDIATE_EVALS="${TMX_SKIP_INTERMEDIATE_EVALS:-0}" \
TMX_ALLOW_XLA_GRPO_INTERMEDIATE_SAVE="${TMX_ALLOW_XLA_GRPO_INTERMEDIATE_SAVE:-}" \
TMX_GRPO_SAVE_STRATEGY="${TMX_GRPO_SAVE_STRATEGY:-steps}" \
TMX_GRPO_SAVE_STEPS="${TMX_GRPO_SAVE_STEPS:-4}" \
TMX_GRPO_SAVE_TOTAL_LIMIT="${TMX_GRPO_SAVE_TOTAL_LIMIT:-3}" \
TMX_GRPO_LOGGING_STRATEGY="${TMX_GRPO_LOGGING_STRATEGY:-steps}" \
TMX_GRPO_LOGGING_STEPS="${TMX_GRPO_LOGGING_STEPS:-1}" \
TMX_ABORT_ON_DEGENERATE_EXPLORER="${TMX_ABORT_ON_DEGENERATE_EXPLORER:-1}" \
TMX_ABORT_ON_BAD_TRAJ_WINDOW="${TMX_ABORT_ON_BAD_TRAJ_WINDOW:-1}" \
TMX_TRAJ_HEALTH_WINDOW_PROMPTS="${TMX_TRAJ_HEALTH_WINDOW_PROMPTS:-32}" \
TMX_TRAJ_HEALTH_MIN_CORRECT="${TMX_TRAJ_HEALTH_MIN_CORRECT:-1}" \
TMX_TRAJ_TARGET_ACCEPTED="${TMX_TRAJ_TARGET_ACCEPTED:-48}" \
TMX_USE_XLA_WORLD_SIZE="${TMX_USE_XLA_WORLD_SIZE:-}" \
RUN_ARTIFACT_GCS_PREFIX="$RUN_ARTIFACT_GCS_PREFIX" \
RUN_SYNC_INTERVAL_SECONDS="${RUN_SYNC_INTERVAL_SECONDS:-90}" \
TPU_NAME="$TPU_NAME" \
ZONE="$ZONE" \
WORKERS="${WORKERS:-0}" \
SYNC_WORKERS="${SYNC_WORKERS:-0}" \
BOOTSTRAP_WORKERS="${BOOTSTRAP_WORKERS:-0}" \
CHIPS="${CHIPS:-0}" \
LOCAL_CHIPS="${LOCAL_CHIPS:-1}" \
SKIP_BOOTSTRAP="${SKIP_BOOTSTRAP:-0}" \
ALLOW_DIRTY=1 \
RUN_PROFILE="${RUN_PROFILE:-dapo_standard}" \
RECIPE_MODE="${RECIPE_MODE:-dapo_standard_baseinit}" \
RUN_OFFSET="${RUN_OFFSET:-0}" \
RUN_LIMIT="${RUN_LIMIT:-1}" \
SEED="${SEED:-0}" \
QUEUE_TAG="$QUEUE_TAG" \
SESSION_PREFIX="${SESSION_PREFIX:-ew4a_q3dapo}" \
MODEL_NAME="${MODEL_NAME:-Qwen/Qwen3-1.7B}" \
DATASET_NAME="${DATASET_NAME:-dapo_math_17k}" \
MAX_TRAIN_EXAMPLES="${MAX_TRAIN_EXAMPLES:-512}" \
MAX_EVAL_EXAMPLES="${MAX_EVAL_EXAMPLES:-128}" \
TRAIN_PROBE_POOL_SIZE="${TRAIN_PROBE_POOL_SIZE:-512}" \
TRAIN_PROBE_SAMPLES_PER_PROMPT="${TRAIN_PROBE_SAMPLES_PER_PROMPT:-4}" \
TRAIN_PROBE_BATCH_SIZE="${TRAIN_PROBE_BATCH_SIZE:-4}" \
GRPO_MAX_STEPS="${GRPO_MAX_STEPS:-12}" \
GRPO_NUM_GENERATIONS="${GRPO_NUM_GENERATIONS:-2}" \
GRPO_GENERATION_BATCH_SIZE="${GRPO_GENERATION_BATCH_SIZE:-1}" \
NUM_SAMPLES_PER_PROMPT="${NUM_SAMPLES_PER_PROMPT:-2}" \
MAX_PROMPT_LEN="${MAX_PROMPT_LEN:-256}" \
MAX_COMPLETION_LEN="${MAX_COMPLETION_LEN:-192}" \
EXPLORATION_MAX_COMPLETION_LEN="${EXPLORATION_MAX_COMPLETION_LEN:-96}" \
EVAL_MAX_COMPLETION_LEN="${EVAL_MAX_COMPLETION_LEN:-128}" \
MAX_TOTAL_LEN="${MAX_TOTAL_LEN:-384}" \
DISTILL_EPOCHS="${DISTILL_EPOCHS:-2}" \
MAX_DISTILL_EXAMPLES="${MAX_DISTILL_EXAMPLES:-512}" \
ACTUAL_GRPO_EPOCHS="${ACTUAL_GRPO_EPOCHS:-3}" \
ACTUAL_GRPO_BATCH_SIZE="${ACTUAL_GRPO_BATCH_SIZE:-1}" \
ACTUAL_MIN_ACCEPTED_TRAJECTORIES="${ACTUAL_MIN_ACCEPTED_TRAJECTORIES:-8}" \
MAX_ACTUAL_EXAMPLES="${MAX_ACTUAL_EXAMPLES:-512}" \
NOVELTY_FEATURE_SOURCE="${NOVELTY_FEATURE_SOURCE:-last}" \
NOVELTY_FEATURE_MAX_LENGTH="${NOVELTY_FEATURE_MAX_LENGTH:-128}" \
ANSWER_CONSTRAINT_MODE="${ANSWER_CONSTRAINT_MODE:-}" \
EXPLORATION_RESPONSE_STYLE="${EXPLORATION_RESPONSE_STYLE:-}" \
EVAL_RESPONSE_STYLE="${EVAL_RESPONSE_STYLE:-}" \
EXPLORATION_ANSWER_CONSTRAINT_MODE="${EXPLORATION_ANSWER_CONSTRAINT_MODE:-}" \
EVAL_ANSWER_CONSTRAINT_MODE="${EVAL_ANSWER_CONSTRAINT_MODE:-}" \
EXPLORATION_THINKING_MODE="${EXPLORATION_THINKING_MODE:-think}" \
EVAL_THINKING_MODE="${EVAL_THINKING_MODE:-think}" \
ACTUAL_TARGET_CONTRACT="${ACTUAL_TARGET_CONTRACT:-}" \
BASE_EVAL_MODE="${BASE_EVAL_MODE:-raw}" \
REWARD_CORRECT="${REWARD_CORRECT:-1.0}" \
REWARD_INCORRECT="${REWARD_INCORRECT:--1.0}" \
REWARD_SHAPE="${REWARD_SHAPE:-piecewise}" \
INCORRECT_NOVELTY_SCALE="${INCORRECT_NOVELTY_SCALE:-0.0}" \
FORMAT_PENALTY_WEIGHT="${FORMAT_PENALTY_WEIGHT:-0.2}" \
SAVE_BASE_MODEL="${SAVE_BASE_MODEL:-0}" \
SAVED_MODEL_ROOT="${SAVED_MODEL_ROOT:?set SAVED_MODEL_ROOT to the saved-model directory on the TPU VM}" \
TRAIN_SELECTION_POLICY="${TRAIN_SELECTION_POLICY:-random}" \
bash scripts/queue_gsm8k_recipe_search_tmux.sh

log "launch complete; rerun with same QUEUE_TAG to resume"
