#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

RUN_NAME="${RUN_NAME:-dapo16k_drgrpo_novelty025_saif_v6efulltrain_v5serve_jaxplatform_$(date +%Y%m%d_%H%M%S)}"

export TMX_JAX_REPO="${TMX_JAX_REPO:-$(cd "$ROOT/../tmx-jax" && pwd)}"
export RUN_NAME

export TRAIN_TPU_NAME="${TRAIN_TPU_NAME:?set TRAIN_TPU_NAME to the training TPU VM (slice) name}"
export TRAIN_TPU_PROJECT="${TRAIN_TPU_PROJECT:?set TRAIN_TPU_PROJECT to the GCP project id of the training TPU}"
export TRAIN_ZONE="${TRAIN_ZONE:-europe-west4-a}"
export SERVE_TPU_NAME="${SERVE_TPU_NAME:?set SERVE_TPU_NAME to the serving (vLLM) TPU VM (slice) name}"
export SERVE_TPU_PROJECT="${SERVE_TPU_PROJECT:?set SERVE_TPU_PROJECT to the GCP project id of the serving TPU}"
export SERVE_ZONE="${SERVE_ZONE:-europe-west4-b}"
export TRAIN_WORKERS="${TRAIN_WORKERS:-0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15}"
export SERVE_WORKERS="${SERVE_WORKERS:-0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15}"

export BOOTSTRAP_SERVE_VLLM="${BOOTSTRAP_SERVE_VLLM:-0}"
export VERIFY_EXISTING_SERVE_VLLM="${VERIFY_EXISTING_SERVE_VLLM:-1}"
export CLEAN_SERVE_SLICE="${CLEAN_SERVE_SLICE:-0}"
export ALLOW_DEGRADED_SERVE="${ALLOW_DEGRADED_SERVE:-1}"
export MIN_HEALTHY_SERVE_WORKERS="${MIN_HEALTHY_SERVE_WORKERS:-12}"

export MODEL_NAME="${MODEL_NAME:-Qwen/Qwen3-1.7B}"
export MAX_PROMPT_LEN="${MAX_PROMPT_LEN:-2048}"
export MAX_COMPLETION_LEN="${MAX_COMPLETION_LEN:-16384}"
export MAX_TOTAL_LEN="${MAX_TOTAL_LEN:-18432}"
# Full 64-chip train mesh requires rows divisible by mesh size.
# With G=16, batch=4 gives 64 rollout rows per optimizer step.
export GRPO_BATCH_SIZE="${GRPO_BATCH_SIZE:-4}"
export GRPO_GRAD_ACCUM="${GRPO_GRAD_ACCUM:-1}"
export GRPO_NUM_GENERATIONS="${GRPO_NUM_GENERATIONS:-16}"
export GRPO_MAX_STEPS="${GRPO_MAX_STEPS:-100}"
export GRPO_LR="${GRPO_LR:-5e-6}"
export GRPO_CLIP_EPSILON=0.2
export GRPO_CLIP_EPSILON_HIGH=0.28
export GRPO_KL_BETA=0.0
export GRPO_ADVANTAGE_NORMALIZATION=none
export DYNAMIC_SAMPLING=true
export DYNAMIC_SAMPLING_MAX_ATTEMPTS="${DYNAMIC_SAMPLING_MAX_ATTEMPTS:-8}"
export DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT="${DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT:-1}"
export TMX_DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT="${TMX_DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT:-1}"
export REWARD_CORRECT=1.0
export REWARD_INCORRECT=-1.0
export FORMAT_PENALTY_WEIGHT=0.0
export TMX_APPLY_FORMAT_PENALTY=0
export LAMBDA_NOVELTY="${LAMBDA_NOVELTY:-0.25}"
export NOVELTY_LAYERS="${NOVELTY_LAYERS:-7,14,21}"
export NOVELTY_METRIC="${NOVELTY_METRIC:-sqrt_mse}"
export INCORRECT_NOVELTY_SCALE="${INCORRECT_NOVELTY_SCALE:-1.0}"
export SOFT_OVERLONG_EXPECTED_LEN="${SOFT_OVERLONG_EXPECTED_LEN:-13107}"
export SOFT_OVERLONG_CACHE_LEN="${SOFT_OVERLONG_CACHE_LEN:-3277}"

export TMX_PIPELINE_STAGE="${TMX_PIPELINE_STAGE:-explorer_novelty}"
export TMX_PIPELINE_STOP_AFTER_EXPLORER="${TMX_PIPELINE_STOP_AFTER_EXPLORER:-1}"
export TMX_FRESH_RUN="${TMX_FRESH_RUN:-1}"
export SAVE_EVERY_STEPS="${SAVE_EVERY_STEPS:-25}"
export TMX_HF_CHECKPOINT_EVERY_STEPS="${TMX_HF_CHECKPOINT_EVERY_STEPS:-25}"
export TMX_REQUIRE_HF_ARTIFACT_UPLOAD="${TMX_REQUIRE_HF_ARTIFACT_UPLOAD:-1}"
export TMX_ARTIFACT_BACKEND=hf
export TMX_ALLOW_GCS_ARTIFACTS=0
export TMX_GCS_CHECKPOINT_BASE=
export TMX_HF_CHECKPOINT_REPO="${TMX_HF_CHECKPOINT_REPO:-SaifPunjwani/two-model-exploration-checkpoints}"
export TMX_HF_MODEL_REPO="${TMX_HF_MODEL_REPO:-SaifPunjwani/two-model-exploration-models}"
export TMX_HF_DATASET_REPO="${TMX_HF_DATASET_REPO:-SaifPunjwani/two-model-exploration-checkpoints}"
export TMX_HF_REPO_TYPE="${TMX_HF_REPO_TYPE:-dataset}"
export TMX_HF_ARTIFACT_PREFIX="${TMX_HF_ARTIFACT_PREFIX:-$RUN_NAME}"
export HF_HUB_ENABLE_HF_TRANSFER="${HF_HUB_ENABLE_HF_TRANSFER:-0}"

export TMX_WANDB_MINIMAL=1
export TMX_WANDB_SINGLE_RUN=1
export WANDB_PROJECT="${WANDB_PROJECT:-two-model-explore}"
export WANDB_ENTITY="${WANDB_ENTITY:-}"

export VLLM_CONCURRENCY="${VLLM_CONCURRENCY:-64}"
export VLLM_FANOUT_PER_PROMPT="${VLLM_FANOUT_PER_PROMPT:-16}"
export VLLM_MAX_MODEL_LEN="${VLLM_MAX_MODEL_LEN:-18432}"
export VLLM_MAX_NUM_SEQS="${VLLM_MAX_NUM_SEQS:-1}"
export VLLM_MAX_NUM_BATCHED_TOKENS="${VLLM_MAX_NUM_BATCHED_TOKENS:-18432}"
export TMX_TRAIN_VLLM_RELOAD_MODE="${TMX_TRAIN_VLLM_RELOAD_MODE:-external}"
export TMX_TRAIN_VLLM_RELOAD_EVERY_STEPS="${TMX_TRAIN_VLLM_RELOAD_EVERY_STEPS:-25}"
export TMX_TRAIN_VLLM_RELOAD_FIRST_STEP="${TMX_TRAIN_VLLM_RELOAD_FIRST_STEP:-1}"

export JAX_PLATFORMS="${JAX_PLATFORMS:-tpu}"
export PJRT_DEVICE="${PJRT_DEVICE:-TPU}"
export JAX_HEARTBEAT_TIMEOUT_SECONDS="${JAX_HEARTBEAT_TIMEOUT_SECONDS:-900}"
export TMX_TRAIN_LAUNCH_STABILITY_SECONDS="${TMX_TRAIN_LAUNCH_STABILITY_SECONDS:-3}"

exec scripts/restart_dapo_drgrpo_twoslice.sh
