#!/usr/bin/env bash
set -euo pipefail

# Production fallback path for the lambda=0.5 Explorer continuation.
# Uses the proven raw TPU tmx-jax two-slice topology:
# - full v6e-64 slice for JAX training
# - full v5litepod-64 slice for vLLM rollouts
# - HF-only artifacts, no GCS storage writes

export RUN_NAME="${RUN_NAME:-dapo16k_drgrpo_novelty05_v6etrain_v5serve_resume100_$(date +%Y%m%d_%H%M%S)}"
export SOURCE_RUN="${SOURCE_RUN:-dapo16k_drgrpo_novelty05_hf_resume49_20260429_174651_wandbresume_parallelvllm}"
export SOURCE_STEP="${SOURCE_STEP:-000100}"
export INIT_CHECKPOINT="${INIT_CHECKPOINT:-hf://SaifPunjwani/two-model-exploration-checkpoints/${SOURCE_RUN}/explorer/checkpoints/step_${SOURCE_STEP}}"

# DAPO / Dr.GRPO contract.
export GRPO_BATCH_SIZE="${GRPO_BATCH_SIZE:-4}"
export GRPO_GRAD_ACCUM="${GRPO_GRAD_ACCUM:-1}"
export GRPO_NUM_GENERATIONS="${GRPO_NUM_GENERATIONS:-16}"
export GRPO_MAX_STEPS="${GRPO_MAX_STEPS:-300}"
export GRPO_UPDATES_PER_ROLLOUT="${GRPO_UPDATES_PER_ROLLOUT:-1}"
export GRPO_LR="${GRPO_LR:-5e-6}"
export MAX_PROMPT_LEN=2048
export MAX_COMPLETION_LEN=16384
export MAX_TOTAL_LEN=18432
export SOFT_OVERLONG_EXPECTED_LEN=13107
export SOFT_OVERLONG_CACHE_LEN=3277
export LAMBDA_NOVELTY=0.5
export INCORRECT_NOVELTY_SCALE=1.0
export GRPO_CLIP_EPSILON=0.2
export GRPO_CLIP_EPSILON_HIGH=0.28
export GRPO_KL_BETA=0.0
export GRPO_ADVANTAGE_NORMALIZATION=none
export DYNAMIC_SAMPLING=true
export DYNAMIC_SAMPLING_MAX_ATTEMPTS="${DYNAMIC_SAMPLING_MAX_ATTEMPTS:-2}"
export DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT="${DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT:-2}"
export TMX_DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT="$DYNAMIC_SAMPLING_GROUPS_PER_ATTEMPT"
export TMX_DYNAMIC_SAMPLING_ACCEPT_REWARD_VARIANCE=1
export MASK_TRUNCATED_COMPLETIONS=false
export REWARD_CORRECT=1.0
export REWARD_INCORRECT=-1.0
export FORMAT_PENALTY_WEIGHT=0.0
export NONTERMINATION_PENALTY=0.0
export INVALID_ANSWER_PENALTY=0.0

# Train on full v6e-64 in europe-west4-a.
export TPU_PROJECT="${TPU_PROJECT:?set TPU_PROJECT to the GCP project id of the TPU}"
export TRAIN_TPU_PROJECT="${TRAIN_TPU_PROJECT:?set TRAIN_TPU_PROJECT to the GCP project id of the training TPU}"
export TRAIN_TPU_NAME="${TRAIN_TPU_NAME:?set TRAIN_TPU_NAME to the training TPU VM (slice) name}"
export TRAIN_ZONE=europe-west4-a
export TPU_ACCELERATOR_TYPE=v6e-64
export TRAIN_WORKERS="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15"

# Serve rollouts on full v5litepod-64 in the same GCP region.
export SERVE_TPU_PROJECT="${SERVE_TPU_PROJECT:?set SERVE_TPU_PROJECT to the GCP project id of the serving TPU}"
export SERVE_TPU_NAME="${SERVE_TPU_NAME:?set SERVE_TPU_NAME to the serving (vLLM) TPU VM (slice) name}"
export SERVE_ZONE=europe-west4-b
export SERVE_WORKERS="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15"
export TMX_REQUIRE_SAME_REGION_TPU=1
export TMX_ALLOW_CROSS_REGION_TPU=0

# vLLM and reload/probe cadence.
export VLLM_MAX_MODEL_LEN="$MAX_TOTAL_LEN"
export VLLM_MAX_NUM_BATCHED_TOKENS="$MAX_TOTAL_LEN"
export VLLM_MAX_NUM_SEQS=1
export VLLM_TP_SIZE=4
export VLLM_CONCURRENCY="${VLLM_CONCURRENCY:-96}"
export VLLM_FANOUT_PER_PROMPT=16
export TMX_VLLM_RANDOMIZE_SEEDS=1
export TMX_VLLM_SEED_MODE=prompt_nonce
export TMX_VLLM_SEED_BASE="${TMX_VLLM_SEED_BASE:-${RUN_NAME}}"
export TMX_VLLM_FANOUT_NONCE="${TMX_VLLM_FANOUT_NONCE:-${RUN_NAME}}"
export TMX_HTTP_POOL_MAXSIZE=512
export TMX_VLLM_ENDPOINT_MAX_INFLIGHT=2
export TMX_VLLM_SKIP_FAILED_WORKERS=1
export ALLOW_DEGRADED_SERVE=1
export MIN_HEALTHY_SERVE_WORKERS="${MIN_HEALTHY_SERVE_WORKERS:-12}"
export TMX_PARALLEL_VLLM_HEALTH=1
export TMX_TRAIN_VLLM_RELOAD_MODE=direct
export TMX_TRAIN_VLLM_RELOAD_ON_RESUME="${TMX_TRAIN_VLLM_RELOAD_ON_RESUME:-0}"
export TMX_TRAIN_VLLM_RELOAD_EVERY_STEPS=10
export TMX_TRAIN_VLLM_RELOAD_FIRST_STEP=110
export TMX_VLLM_RELOAD_MIN_HEALTHY_WORKERS=12
export TMX_VLLM_RELOAD_ALLOW_PARALLEL=1
export TMX_VLLM_RELOAD_PARALLELISM=8
# The train TPU can reach the serve TPU directly. Avoid IAP inside TPU VMs:
# it is slower and has repeatedly stranded reload fanout.
export TPU_TRANSPORT_FLAG=direct
export TMX_FAST_CLEAN_MIN_WORKERS=8
export GCLOUD_SSH_CONNECT_TIMEOUT_SECONDS="${GCLOUD_SSH_CONNECT_TIMEOUT_SECONDS:-10}"
export GCLOUD_SSH_SERVER_ALIVE_INTERVAL="${GCLOUD_SSH_SERVER_ALIVE_INTERVAL:-5}"
export GCLOUD_SSH_SERVER_ALIVE_COUNT_MAX="${GCLOUD_SSH_SERVER_ALIVE_COUNT_MAX:-2}"
export TMX_VLLM_SSH_CONNECT_TIMEOUT_SECONDS="${TMX_VLLM_SSH_CONNECT_TIMEOUT_SECONDS:-10}"
export TMX_VLLM_SSH_SERVER_ALIVE_INTERVAL="${TMX_VLLM_SSH_SERVER_ALIVE_INTERVAL:-5}"
export TMX_VLLM_SSH_SERVER_ALIVE_COUNT_MAX="${TMX_VLLM_SSH_SERVER_ALIVE_COUNT_MAX:-2}"
export TMX_AIME_PROBE_EVERY_STEPS=10
export TMX_AIME_PROBE_NUM_PROBLEMS=6
export TMX_AIME_PROBE_NUM_ROLLOUTS=4

# HF-only storage and compact W&B.
export TMX_ARTIFACT_BACKEND=hf
export TMX_ALLOW_GCS_ARTIFACTS=0
export TMX_GCS_CHECKPOINT_BASE=
export TMX_ORBAX_DIRECT_GCS_CHECKPOINT=0
export TMX_REQUIRE_GCS_CHECKPOINT_UPLOAD=0
export TMX_HF_CHECKPOINT_REPO=SaifPunjwani/two-model-exploration-checkpoints
export TMX_HF_MODEL_REPO=SaifPunjwani/two-model-exploration-models
export TMX_HF_DATASET_REPO=SaifPunjwani/two-model-exploration-checkpoints
export TMX_HF_REPO_TYPE=dataset
export TMX_HF_ARTIFACT_PREFIX="$RUN_NAME"
export TMX_HF_CHECKPOINT_EVERY_STEPS=10
export TMX_REQUIRE_HF_ARTIFACT_UPLOAD=1
export SAVE_EVERY_STEPS=10
export TMX_LOCAL_CHECKPOINT_EVERY_STEPS=0
export TMX_SKIP_MULTIHOST_LOCAL_ONLY_CHECKPOINT=1
export TMX_HF_MIRROR_VLLM_EXPORTS=1
export TMX_WANDB_SINGLE_RUN=1
export TMX_WANDB_COMPACT=1
export TMX_WANDB_MINIMAL=1
export TMX_WANDB_EVAL_PROGRESS=0

# Keep the exact full-contract guard active.
export TMX_DAPO_DRGRPO_FULL_CONTRACT=1
export TMX_DAPO_DRGRPO_CONTRACT_COMPLETION_LEN="$MAX_COMPLETION_LEN"
export TMX_DAPO_DRGRPO_CONTRACT_SOFT_OVERLONG_EXPECTED_LEN="$SOFT_OVERLONG_EXPECTED_LEN"
export TMX_DAPO_DRGRPO_CONTRACT_SOFT_OVERLONG_CACHE_LEN="$SOFT_OVERLONG_CACHE_LEN"

scripts/restart_dapo_drgrpo_twoslice.sh
