#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

RUN_NAME="${RUN_NAME:-qwen3_explorer_fit_probe_$(date +%Y%m%d_%H%M%S)}"
WANDB_RUN_NAME="${WANDB_RUN_NAME:-$RUN_NAME}"

ALLOW_DIRTY="${ALLOW_DIRTY:-1}" \
REMOTE_STATE_TARGET="${REMOTE_STATE_TARGET:-train}" \
RUN_NAME="$RUN_NAME" \
WANDB_RUN_NAME="$WANDB_RUN_NAME" \
GRPO_MAX_STEPS="${GRPO_MAX_STEPS:-2}" \
TEMPERATURE_SCHEDULE="${TEMPERATURE_SCHEDULE:-1.0}" \
MAX_TRAIN_EXAMPLES="${MAX_TRAIN_EXAMPLES:-64}" \
MAX_EVAL_EXAMPLES="${MAX_EVAL_EXAMPLES:-4}" \
MAX_DISTILL_EXAMPLES="${MAX_DISTILL_EXAMPLES:-16}" \
MAX_ACTUAL_EXAMPLES="${MAX_ACTUAL_EXAMPLES:-16}" \
DISTILL_EPOCHS="${DISTILL_EPOCHS:-1}" \
ACTUAL_GRPO_EPOCHS="${ACTUAL_GRPO_EPOCHS:-1}" \
EXPDIS_STOP_AFTER_EXPLORER=1 \
EXPDIS_STOP_AFTER_TRAJECTORIES=0 \
EXPDIS_SKIP_INTERMEDIATE_EVALS=1 \
EXPDIS_SKIP_FINAL_BENCHMARK_EVALS=1 \
EXPDIS_FINAL_EVAL_ONLY_ACTUAL=1 \
EXPDIS_FINAL_EVAL_MAX_EXAMPLES=1 \
EXPDIS_WANDB_MINIMAL=1 \
EXPDIS_XLA_INCREMENTAL_GENERATE="${EXPDIS_XLA_INCREMENTAL_GENERATE:-1}" \
EXPDIS_XLA_GENERATE_PROGRESS_EVERY="${EXPDIS_XLA_GENERATE_PROGRESS_EVERY:-64}" \
EXPDIS_DECOUPLED_TRAIN_DEBUG_PROGRESS="${EXPDIS_DECOUPLED_TRAIN_DEBUG_PROGRESS:-1}" \
BOOTSTRAP_PARALLELISM="${BOOTSTRAP_PARALLELISM:-4}" \
VLLM_PREFETCH_PARALLELISM="${VLLM_PREFETCH_PARALLELISM:-4}" \
VLLM_LAUNCH_PARALLELISM="${VLLM_LAUNCH_PARALLELISM:-4}" \
MIN_READY_SERVERS="${MIN_READY_SERVERS:-1}" \
ALLOW_PARTIAL_VLLM_SLICE="${ALLOW_PARTIAL_VLLM_SLICE:-1}" \
PARTIAL_READY_DELAY_ATTEMPTS="${PARTIAL_READY_DELAY_ATTEMPTS:-2}" \
bash scripts/launch_qwen3_explorer_novelty_checked.sh
