#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

RUN_NAME="${RUN_NAME:-qwen3_aime24_avg32_$(date +%Y%m%d_%H%M%S)}"

PYTHON_BIN="${PYTHON_BIN:-}" \
SERVER_BASE_URL="${SERVER_BASE_URL:-http://127.0.0.1:8000/v1}" \
MODEL_NAME="${MODEL_NAME:-Qwen/Qwen3-1.7B}" \
SERVED_MODEL_NAME="${SERVED_MODEL_NAME:-actual_model}" \
TOKENIZER_NAME="${TOKENIZER_NAME:-Qwen/Qwen3-1.7B}" \
RUN_NAME="$RUN_NAME" \
ROLE_NAME="${ROLE_NAME:-actual}" \
BENCHMARK_DATASET_NAME=aime_2024 \
MAX_BENCHMARK="${MAX_BENCHMARK:-30}" \
BENCHMARK_NUM_ROLLOUTS=32 \
BENCHMARK_ROLLOUT_TEMPERATURE="${BENCHMARK_ROLLOUT_TEMPERATURE:-1.0}" \
BENCHMARK_ROLLOUT_TOP_P="${BENCHMARK_ROLLOUT_TOP_P:-1.0}" \
BENCHMARK_ROLLOUT_TOP_K="${BENCHMARK_ROLLOUT_TOP_K:-0}" \
BENCHMARK_ROLLOUT_PASS_K=1,4,8,16,32 \
BENCHMARK_ROLLOUT_MAX_COMPLETION_LEN="${BENCHMARK_ROLLOUT_MAX_COMPLETION_LEN:-16000}" \
REQUEST_CONCURRENCY="${REQUEST_CONCURRENCY:-32}" \
REQUEST_TIMEOUT_SECONDS="${REQUEST_TIMEOUT_SECONDS:-1800}" \
MAX_PROMPT_LEN="${MAX_PROMPT_LEN:-2048}" \
EVAL_RESPONSE_STYLE=reasoning_final \
ANSWER_CONSTRAINT_MODE=none \
THINKING_MODE=think \
USE_WANDB="${USE_WANDB:-1}" \
WANDB_GROUP="${WANDB_GROUP:-qwen3_saved_aime24_avg32}" \
bash scripts/run_vllm_aime_rollout_eval.sh
