#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [ -n "${GCS_MODEL_PATH:-}" ]; then
  TPU_NAME="${INFER_TPU_NAME:?set INFER_TPU_NAME to the inference (vLLM) TPU VM (slice) name}" \
  ZONE="${INFER_ZONE:-europe-west4-b}" \
  WORKERS="${RELOAD_WORKERS:-all}" \
  SERVED_MODEL_NAME="${SERVED_MODEL_NAME:-actual_model}" \
  PORT="${PORT:-8000}" \
  TP_SIZE="${TP_SIZE:-4}" \
  MAX_MODEL_LEN="${MAX_MODEL_LEN:-16384}" \
  MAX_NUM_SEQS="${MAX_NUM_SEQS:-32}" \
  MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-65536}" \
  VLLM_VENV_DIR="${VLLM_VENV_DIR:?set VLLM_VENV_DIR to the vLLM virtualenv path on the serving TPU VM}" \
  REMOTE_ROOT="${REMOTE_ROOT:?set REMOTE_ROOT to the absolute repo checkout path on the TPU VM}" \
  GCS_MODEL_PATH="$GCS_MODEL_PATH" \
  bash scripts/reload_vllm_slice_with_model.sh
fi

RUN_PREFIX="${RUN_PREFIX:-qwen3_aime24_avg32_sharded_$(date +%Y%m%d_%H%M%S)}" \
TPU_NAME="${INFER_TPU_NAME:?set INFER_TPU_NAME to the inference (vLLM) TPU VM (slice) name}" \
ZONE="${INFER_ZONE:-europe-west4-b}" \
MODEL_NAME="${MODEL_NAME:-Qwen/Qwen3-1.7B}" \
SERVED_MODEL_NAME="${SERVED_MODEL_NAME:-actual_model}" \
TOKENIZER_NAME="${TOKENIZER_NAME:-Qwen/Qwen3-1.7B}" \
WORKERS="${WORKERS:-all}" \
SYNC_REPO="${SYNC_REPO:-0}" \
BOOTSTRAP_VLLM="${BOOTSTRAP_VLLM:-0}" \
WAIT_FOR_COMPLETION="${WAIT_FOR_COMPLETION:-1}" \
SKIP_SERVER_LAUNCH="${SKIP_SERVER_LAUNCH:-1}" \
PORT="${PORT:-8000}" \
TP_SIZE="${TP_SIZE:-4}" \
MAX_MODEL_LEN="${MAX_MODEL_LEN:-16384}" \
MAX_NUM_SEQS="${MAX_NUM_SEQS:-32}" \
MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-65536}" \
BENCHMARK_DATASET_NAME=aime_2024 \
MAX_BENCHMARK="${MAX_BENCHMARK:-30}" \
BENCHMARK_NUM_ROLLOUTS=32 \
BENCHMARK_ROLLOUT_TEMPERATURE="${BENCHMARK_ROLLOUT_TEMPERATURE:-1.0}" \
BENCHMARK_ROLLOUT_TOP_P="${BENCHMARK_ROLLOUT_TOP_P:-1.0}" \
BENCHMARK_ROLLOUT_TOP_K="${BENCHMARK_ROLLOUT_TOP_K:-0}" \
BENCHMARK_ROLLOUT_PASS_K=1,4,8,16,32 \
BENCHMARK_ROLLOUT_MAX_COMPLETION_LEN="${BENCHMARK_ROLLOUT_MAX_COMPLETION_LEN:-16000}" \
REQUEST_CONCURRENCY="${REQUEST_CONCURRENCY:-32}" \
REQUEST_TIMEOUT_SECONDS="${REQUEST_TIMEOUT_SECONDS:-1800}" \
MAX_PROMPT_LEN="${MAX_PROMPT_LEN:-2048}" \
EVAL_RESPONSE_STYLE=reasoning_final \
ANSWER_CONSTRAINT_MODE=none \
THINKING_MODE=think \
USE_WANDB="${USE_WANDB:-1}" \
WANDB_GROUP="${WANDB_GROUP:-qwen3_saved_aime24_avg32_sharded}" \
bash scripts/run_tpu_slice_vllm_sharded_aime.sh
